name: awesome_design_system_widgetbook
description: Widgetbook for the Awesome Design System
version: 0.1.0
publish_to: none

environment:
  sdk: "^3.9.0"
  flutter: ">=3.22.0"

resolution: workspace

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.7.0
  widgetbook_annotation: ^3.1.0
  awesome_design_system_tokens:
    path: ../packages/tokens
  awesome_design_system_atoms:
    path: ../packages/atoms
  awesome_design_system_molecules:
    path: ../packages/molecules
  awesome_design_system_organisms:
    path: ../packages/organisms

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.7.0
  build_runner: ^2.4.0