name: awesome_design_system_atoms
description: Atomic components for the Awesome Design System
version: 0.1.0
publish_to: none

environment:
  sdk: "^3.9.0"
  flutter: ">=3.22.0"

resolution: workspace

dependencies:
  awesome_design_system_tokens:
    path: ../tokens
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
